// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb2Pqd0-dkoNnh0rPJ2_0KCjUuYM4Z0UQ',
    appId: '1:251864479113:web:5fad80c4de197a46f39d58',
    messagingSenderId: '251864479113',
    projectId: 'whatsapp-clone-backend-7e2c0',
    authDomain: 'whatsapp-clone-backend-7e2c0.firebaseapp.com',
    storageBucket: 'whatsapp-clone-backend-7e2c0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKWKX64Pq06e9kbg_q0W9m5pauru_lnKY',
    appId: '1:251864479113:android:ff8ab0fc2c48f1bff39d58',
    messagingSenderId: '251864479113',
    projectId: 'whatsapp-clone-backend-7e2c0',
    storageBucket: 'whatsapp-clone-backend-7e2c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCftQHRxo-oD9BqGr1i1CUxcxCiSdWW084',
    appId: '1:251864479113:ios:b684d6ebd03e8396f39d58',
    messagingSenderId: '251864479113',
    projectId: 'whatsapp-clone-backend-7e2c0',
    storageBucket: 'whatsapp-clone-backend-7e2c0.appspot.com',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCftQHRxo-oD9BqGr1i1CUxcxCiSdWW084',
    appId: '1:251864479113:ios:f7b5267eaf5d5b52f39d58',
    messagingSenderId: '251864479113',
    projectId: 'whatsapp-clone-backend-7e2c0',
    storageBucket: 'whatsapp-clone-backend-7e2c0.appspot.com',
    iosBundleId: 'com.example.whatsappClone.RunnerTests',
  );
}
